#conda env create -f environment.yml    通过以下命令创建相同的环境

name: myenv
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - absl-py==2.1.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastapi==0.115.12
      - fonttools==4.56.0
      - gitdb==4.0.12
      - GitPython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - h11==0.14.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - jedi==0.19.2
      - Jinja2==3.1.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.7
      - labelImg==1.8.6
      - lxml==5.3.1
      - MaixPy==4.10.3
      - Markdown==3.7
      - MarkupSafe==3.0.2
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mkl-fft==1.3.11
      - mkl-random==1.2.8
      - mkl-service==2.4.0
      - narwhals==1.31.0
      - numpy==1.23.5
      - oauthlib==3.2.2
      - opencv-contrib-python-headless==4.11.0.86
      - opencv-python==4.10.0.84
      - packaging==24.2
      - paddlepaddle==2.6.2
      - pandas==2.0.3
      - parso==0.8.4
      - pillow==10.4.0
      - pip==25.0
      - prompt-toolkit==3.0.50
      - protobuf==4.21.2
      - psutil==7.0.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pydeck==0.9.1
      - Pygments==2.19.1
      - pyparsing==3.2.1
      - PyQt5==5.15.11
      - PyQt5-Qt5==5.15.2
      - PyQt5-sip==12.17.0
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.1
      - PyYAML==6.0.2
      - referencing==0.36.2
      - reportlab==4.3.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rpds-py==0.23.1
      - rsa==4.9
      - scipy==1.10.1
      - seaborn==0.13.2
      - sensor==6
      - setuptools==80.4.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.46.1
      - streamlit==1.43.2
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1.post2209072238
      - toml==0.10.2
      - torch==1.10.1
      - torchaudio==0.10.1
      - torchvision==0.11.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2025.1
      - ultralytics==8.3.133
      - ultralytics-thop==2.0.14
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - Werkzeug==3.1.3
      - wheel==0.45.1
      - zipp==3.21.0